import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: 'full',
    justifyContent: 'space-between',
    backgroundColor: '#c5d9ed',
  },
  inputContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight:'bold',
    color:'white',
    backgroundColor: 'navy',
    textAlign: 'center',
    width:350,
    margin:4,
    padding:4,
    borderRadius: 4,
  },
  subTitle: {
    fontSize: 16,
    // fontWeight:'bold',
    color:'white',
    backgroundColor: 'navy',
    textAlign: 'center',
    width:350,
    marginHorizontal:4,
    marginTop:32,
    padding:4,
    borderRadius: 4,
  },
  label: {
    color:'#0a4b78',
    marginTop: 4,
  },
  buttons: {
    // display:'flex',
    // flexDirection:'row',
    // justifyContent:'center',
    // alignItems:'center',
    margin:-16,
  },
  buttonText: {
    letterSpacing:2,
    fontWeight:'bold',
    color: 'navy',
    fontSize: 15,
  },
  buttonRight: {
    position: 'absolute',
    right: 0,
    bottom: 24,
    padding: 24,
    backgroundColor: '#f0f0f0',
    borderRadius: 25,
    borderWidth: 2,
  },
  buttonLeft: {
    position: 'absolute',
    left: 0,
    bottom: 24,
    padding: 24,
    backgroundColor: '#f0f0f0',
    borderRadius: 25,
    borderWidth: 2,
  },
  input: {
    borderWidth: 2,
    borderRadius: 4,
    margin: 4,
    padding: 4,
  },
  insufficientFunds: {
    margin: 15,
    padding: 15,
    borderColor: 'red',
    borderWidth: 1,
    borderRadius: 15,
    alignItems: 'center',
    backgroundColor: '#FF9999'
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 2,
    textAlign: 'center',
    borderWidth:1,
  },
  cell: {
    margin: 8,
    // fontSize: 12,
    width:60,
    textAlign: 'center',
  },
  topCell: {
    // margin: 10,
    fontWeight:'bold',
    width:60,
    fontSize: 10,
    textAlign: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  tabla: {
    margin: 10,
    maxWidth: 330,
  },
});