export * from './calcularCuota';
export * from './calcularEdad';
export * from './calcularIngresos';
export * from './calcularPrestamoMaximo';
export * from './calcularPrimeraCuota';
export * from './calcularSeguroDesempleo';
export * from './calcularTablaAmortizacion';
export * from './exportToExcel';
export * from './formatoConComas';
